from gpiozero import LED
from time import sleep
from switch import speed 
#led 제어
#dot 1 pin할당
#dot 1 pin
dot1 = LED(17)
dot2 = LED(27)
dot3 = LED(22)
dot4 = LED(23)
dot5 = LED(24)
dot6 = LED(25)
#dot 2
#dot1_1 = LED(5)
#dot1_2 = LED(6)
#dot1_3 = LED(19)
#dot1_4 = LED(16)
#dot1_5 = LED(26)
#dot1_6 = LED(20)

#word list 
first_word_list = ['ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅅ', 'ㅇ', 'ㅈ'
                   , 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ', 'ㄲ', 'ㄸ', 'ㅃ', 'ㅆ', 'ㅉ'
                   , 'ㄳ', 'ㄵ', 'ㄶ', 'ㄺ', 'ㄻ', 'ㄼ', 'ㄽ', 'ㄾ', 'ㄿ', 'ㅀ'
                   , 'ㅄ']

middle_word_list = ['ㅏ', 'ㅐ', 'ㅑ', 'ㅒ', 'ㅓ', 'ㅔ', 'ㅕ', 'ㅖ', 'ㅗ'
                    , 'ㅘ', 'ㅙ', 'ㅚ', 'ㅛ', 'ㅜ', 'ㅝ', 'ㅞ', 'ㅟ', 'ㅠ', 'ㅡ', 'ㅢ', 'ㅣ']

num_word_list = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']

abc_word_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'
                 , 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x'
                 , 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'
                 , 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V'
                 , 'W', 'X', 'Y', 'Z']

dot2_word_list = ['ㄱ', 'ㄴ', 'ㄷ', 'ㄹ', 'ㅁ', 'ㅂ', 'ㅅ', 'ㅇ', 'ㅈ'
                   , 'ㅊ', 'ㅋ', 'ㅌ', 'ㅍ', 'ㅎ', 'ㅏ', 'ㅐ', 'ㅑ', 'ㅓ', 'ㅔ', 'ㅕ', 'ㅖ', 'ㅗ'
                    , 'ㅘ', 'ㅚ', 'ㅛ', 'ㅜ', 'ㅝ', 'ㅠ', 'ㅡ', 'ㅢ', 'ㅣ', 'a', 'b', 'c', 'd'
                    , 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r'
                    , 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '1', '2', '3', '4', '5', '6'
                    , '7', '8', '9', '0']

def dot2_off(len):
    if any(str in len for str in dot2_word_list):
        dot1_1.off()
        dot1_2.off()
        dot1_3.off()
        dot1_4.off()
        dot1_5.off()
        dot1_6.off()

#점자 스피드 제어
def dots_speed(flag_speed):
    
    if flag_speed == 0 :
        #if 스피드 조절 led가 노랑색일 때
        sleep(1.5)
    if flag_speed == 1 :
        #if 스피드 조절 led가 흰 색일 때
        sleep(1)
    if flag_speed == 2 :
        #if 스피드 조절 led가 빨간 색일 때
        sleep(0.5)
 
#종성 제어
def print_jong(len):
    #print('종성' + sentance)
    if len == 'ㄱ':
        dot1.on()
        dot2.off()
        dot3.off()
        dot4.off()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot1.off()
    if len == 'ㄴ':
        dot1.off()
        dot2.on()
        dot3.off()
        dot4.off()
        dot5.on()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot2.off()
        dot5.off()
    if len == 'ㄷ':
        dot1.off()
        dot2.off()
        dot3.on()
        dot4.off()
        dot5.on()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot3.off()
        dot5.off()
    if len == 'ㄹ':
        dot1.off()
        dot2.on()
        dot3.off()
        dot4.off()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot2.off()
    if len == 'ㅁ':
        dot1.off()
        dot2.on()
        dot3.off()
        dot4.off()
        dot5.off()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot2.off()
        dot6.off()
    if len == 'ㅂ':
        dot1.on()
        dot2.on()
        dot3.off()
        dot4.off()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot2.off()
    if len == 'ㅅ':
        dot1.off()
        dot2.off()
        dot3.on()
        dot4.off()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot3.off()
    if len == 'ㅇ':
        dot1.off()
        dot2.on()
        dot3.on()
        dot4.off()
        dot5.on()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot2.off()
        dot3.off()
        dot5.off()
        dot6.off()
    if len == 'ㅈ':
        dot1.on()
        dot2.off()
        dot3.on()
        dot4.off()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot3.off()
    if len == 'ㅊ':
        dot1.off()
        dot2.on()
        dot3.on()
        dot4.off()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot2.off()
        dot3.off()
    if len == 'ㅋ':
        dot1.off()
        dot2.on()
        dot3.on()
        dot4.off()
        dot5.on()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot2.off()
        dot3.off()
        dot5.off()
    if len == 'ㅌ':
        dot1.off()
        dot2.on()
        dot3.on()
        dot4.off()
        dot5.off()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot2.off()
        dot3.off()
        dot6.off()
    if len == 'ㅍ':
        dot1.off()
        dot2.on()
        dot3.off()
        dot4.off()
        dot5.on()
        dot6.on()
        dot2_off(len)
        sleep(1.5)
        dot2.off()
        dot5.off()
        dot6.off()
    if len == 'ㅎ':
        dot1.off()
        dot2.off()
        dot3.on()
        dot4.off()
        dot5.on()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot3.off()
        dot5.off()
        dot6.off()
    
#초성 제어
def print_first(len):
    #print('초성' + sentance)
    if len == 'ㄱ':
        dot1.off()
        dot2.off()
        dot3.off()
        dot4.on()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot4.off()
    if len == 'ㄴ':
        dot1.on()
        dot2.off()
        dot3.off()
        dot4.on()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot4.off()
    if len == 'ㄷ':
        dot1.off()
        dot2.on()
        dot3.off()
        dot4.on()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot2.off()
        dot4.off()
    if len == 'ㄹ':
        dot1.off()
        dot2.off()
        dot3.off()
        dot4.off()
        dot5.on()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot5.off()
    if len == 'ㅁ':
        dot1.on()
        dot2.off()
        dot3.off()
        dot4.off()
        dot5.on()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot5.off()
    if len == 'ㅂ':
        dot1.off()
        dot2.off()
        dot3.off()
        dot4.on()
        dot5.on()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot4.off()
        dot5.off()
    if len == 'ㅅ':
        dot1.off()
        dot2.off()
        dot3.off()
        dot4.off()
        dot5.off()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot6.off()
    if len == 'ㅇ':
        dot1.off()
        dot2.on()
        dot3.on()
        dot4.off()
        dot5.on()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot2.off()
        dot3.off()
        dot5.off()
        dot6.off()
    if len == 'ㅈ':
        dot1.off()
        dot2.off()
        dot3.off()
        dot4.on()
        dot5.off()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot4.off()
        dot6.off()
    if len == 'ㅊ':
        dot1.off()
        dot2.off()
        dot3.off()
        dot4.off()
        dot5.on()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot5.off()
        dot6.off()
    if len == 'ㅋ':
        dot1.on()
        dot2.on()
        dot3.off()
        dot4.on()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot2.off()
        dot4.off()
    if len == 'ㅌ':
        dot1.on()
        dot2.on()
        dot3.off()
        dot4.off()
        dot5.on()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot2.off()
        dot5.off()
    if len == 'ㅍ':
        dot1.on()
        dot2.off()
        dot3.off()
        dot4.on()
        dot5.on()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot4.off()
        dot5.off()
    if len == 'ㅎ':
        dot1.off()
        dot2.on()
        dot3.off()
        dot4.on()
        dot5.on()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot2.off()
        dot4.off()
        dot5.off()    
    
#모음 제어
def print_middle(len):
    #print('모음' + sentance)
    if len == 'ㅏ':
        dot1.on()
        dot2.on()
        dot3.off()
        dot4.off()
        dot5.off()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot2.off()
        dot6.off()
    if len == 'ㄴ':
        dot1.off()
        dot2.off()
        dot3.on()
        dot4.on()
        dot5.on()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot4.off()
        dot5.off()
        dot3.off()
    if len == 'ㅓ':
        dot1.off()
        dot2.on()
        dot3.on()
        dot4.on()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot2.off()
        dot3.off()
        dot4.off()
    if len == 'ㅕ':
        dot1.on()
        dot2.off()
        dot3.off()
        dot4.off()
        dot5.on()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot5.off()
        dot6.off()
    if len == 'ㅗ':
        dot1.on()
        dot2.off()
        dot3.on()
        dot4.off()
        dot5.off()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot3.off()
        dot6.off()
    if len == 'ㅛ':
        dot1.off()
        dot2.off()
        dot3.on()
        dot4.on()
        dot5.off()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot3.off()
        dot4.off()
        dot6.off()
    if len == 'ㅜ':
        dot1.on()
        dot2.off()
        dot3.on()
        dot4.off()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot3.off()
        dot4.off()
    if len == 'ㅠ':
        dot1.on()
        dot2.off()
        dot3.off()
        dot4.on()
        dot5.off()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot4.off()
        dot6.off()
    if len == 'ㅡ':
        dot1.off()
        dot2.on()
        dot3.off()
        dot4.on()
        dot5.off()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot2.off()
        dot4.off()
        dot6.off()
    if len == 'ㅐ':
        dot1.on()
        dot2.on()
        dot3.on()
        dot4.off()
        dot5.on()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot2.off()
        dot3.off()
        dot5.off()
    if len == 'ㅔ':
        dot1.on()
        dot2.off()
        dot3.on()
        dot4.on()
        dot5.on()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot3.off()
        dot4.off()
        dot5.off()
    if len == 'ㅚ':
        dot1.on()
        dot2.off()
        dot3.on()
        dot4.on()
        dot5.on()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot3.off()
        dot4.off()
        dot5.off()
        dot6.off()
    if len == 'ㅘ':
        dot1.on()
        dot2.on()
        dot3.on()
        dot4.off()
        dot5.off()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot2.off()
        dot3.off()
        dot6.off()
    if len == 'ㅝ':
        dot1.on()
        dot2.on()
        dot3.on()
        dot4.on()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot1.off()
        dot2.off()
        dot3.off()
        dot4.off()
    if len == 'ㅢ':
        dot1.on()
        dot2.off()
        dot3.on()
        dot4.on()
        dot5.on()
        dot6.on()
        dot2_off(len)
        dots_speed()
        dot2.off()
        dot4.off()
        dot5.off()
        dot6.off()
    if len == 'ㅖ':
        dot1.off()
        dot2.off()
        dot3.on()
        dot4.on()
        dot5.off()
        dot6.off()
        dot2_off(len)
        dots_speed()
        dot3.off()
        dot4.off()
    if len == 'ㅟ':
        dot1.on()
        dot2.off()
        dot3.on()
        dot4.on()
        dot5.off()
        dot6.off()
        dot1_1.on()
        dot1_2.on()
        dot1_3.on()
        dot1_4.off()
        dot1_5.off()
        dot1_6.on()
        dots_speed()
        dot1.off()
        dot3.off()
        dot4.off()
        dot1_1.off()
        dot1_2.off()
        dot1_3.off()
        dot1_5.off() 
    if len == 'ㅒ':
        dot1.off()
        dot2.off()
        dot3.on()
        dot4.on()
        dot5.on()
        dot6.off()
        dot1_1.on()
        dot1_2.on()
        dot1_3.on()
        dot1_4.off()
        dot1_5.off()
        dot1_6.on()
        dots_speed()
        dot3.off()
        dot4.off()
        dot5.off()
        dot1_1.off()
        dot1_2.off()
        dot1_3.off()
        dot1_5.off() 
    if len == 'ㅙ':
        dot1.on()
        dot2.off()
        dot3.on()
        dot4.off()
        dot5.off()
        dot6.on()
        dot1_1.on()
        dot1_2.on()
        dot1_3.on()
        dot1_4.off()
        dot1_5.off()
        dot1_6.on()
        dots_speed()
        dot1.off()
        dot2.off()
        dot3.off()
        dot6.off()
        dot1_1.off()
        dot1_2.off()
        dot1_3.off()
        dot1_5.off()  
    if len == 'ㅞ':
        dot1.on()
        dot2.on()
        dot3.on()
        dot4.on()
        dot5.off()
        dot6.off()
        dot1_1.on()
        dot1_2.on()
        dot1_3.on()
        dot1_4.off()
        dot1_5.off()
        dot1_6.on()
        dots_speed()
        dot1.off()
        dot2.off()
        dot3.off()
        dot4.off()
        dot1_1.off()
        dot1_2.off()
        dot1_3.off()
        dot1_5.off()     


#초성 중성 숫자 제어
def printNum_dot(sentance):
    dot1.off()
    dot2.off()
    dot3.on()
    dot4.on()
    dot5.on()
    dot6.on()
    if len == '0':
        dot1_1.off()
        dot1_2.on()
        dot1_3.off()
        dot1_4.on()
        dot1_5.on()
        dot1_6.off()
        dots_speed()
        dot1_2.off()
        dot1_4.off()
        dot1_5.off()
    if len == '1':
        dot1_1.on()
        dot1_2.off()
        dot1_3.off()
        dot1_4.off()
        dot1_5.off()
        dot1_6.off()
        dots_speed()
        dot1_1.off()
    if len == '2':
        dot1_1.on()
        dot1_2.on()
        dot1_3.off()
        dot1_4.off()
        dot1_5.off()
        dot1_6.off()
        dots_speed()
        dot1_1.off()
        dot1_2.off()
    if len == '3':
        dot1_1.on()
        dot1_2.off()
        dot1_3.off()
        dot1_4.on()
        dot1_5.off()
        dot1_6.off()
        dots_speed()
        dot1_1.off()
        dot1_4.off()
    if len == '4':
        dot1_1.on()
        dot1_2.off()
        dot1_3.off()
        dot1_4.on()
        dot1_5.on()
        dot1_6.off()
        dots_speed()
        dot1_1.off()
        dot1_4.off()
        dot1_5.off()
    if len == '5':
        dot1_1.on()
        dot1_2.off()
        dot1_3.off()
        dot1_4.off()
        dot1_5.on()
        dot1_6.off()
        dots_speed()
        dot1_1.off()
        dot1_5.off()
    if len == '6':
        dot1_1.on()
        dot1_2.on()
        dot1_3.off()
        dot1_4.on()
        dot1_5.off()
        dot1_6.off()
        dots_speed()
        dot1_1.off()
        dot1_2.off()
        dot1_4.off()
    if len == '7':
        dot1_1.on()
        dot1_2.on()
        dot1_3.off()
        dot1_4.on()
        dot1_5.on()
        dot1_6.off()
        dots_speed()
        dot1_1.off()
        dot1_2.off()
        dot1_4.off()
        dot1_5.off()
    if len == '8':
        dot1_1.on()
        dot1_2.on()
        dot1_3.off()
        dot1_4.off()
        dot1_5.on()
        dot1_6.off()
        dots_speed()
        dot1_1.off()
        dot1_2.off()
        dot1_5.off()
    if len == '9':
        dot1_1.off()
        dot1_2.on()
        dot1_3.off()
        dot1_4.on()
        dot1_5.off()
        dot1_6.off()
        dots_speed()
        dot1_2.off()
        dot1_4.off()

    dot3.off()
    dot4.off()
    dot5.off()
    dot6.off()
    print(sentance)


#초성 종성 분리 led제어
def com_len(sentance):
    com = sentance
    com_len = len(com) 
    com.append(" ")
    for i in range(com_len):
        if any(str in com[i+1] for str in '/'):
            if any(str in com[i] for str in first_word_list):
                print_jong(com[i])
        else:
            print_first(com[i])



#input
sentance = ['1', '1', 'ㅇ', 'ㅝ', 'ㄹ', '4', 'ㅇ', 'ㅣ', 'ㄹ'
           , 'ㅇ', 'ㅡ', 'ㄴ', 'ㅈ', 'ㅓ', 'ㅁ', 'ㅈ', 'ㅏ', 'ㅇ', 'ㅢ', 'ㄴ', 'ㅏ', 'ㄹ'
           , 'ㅇ', 'ㅣ', 'ㅂ', 'ㄴ', 'ㅣ', 'ㄷ', 'ㅏ']
#sentance = ['ㅈ', 'ㅓ', 'ㅁ', 'ㅈ', 'ㅏ', 'ㅇ', 'ㅢ', 'ㄴ', 'ㅏ', 'ㄹ'
#           , 'ㅇ', 'ㅣ', 'ㅂ', 'ㄴ', 'ㅣ', 'ㄷ', 'ㅏ']

cnt = len(sentance) #count sentence len
sentance.append("")
for i in range(cnt):
    #종성 구분
    if any(str in sentance[i] for str in first_word_list):
        if any(str in sentance[i-1] for str in middle_word_list):
            if any(str in sentance[i+1] for str in first_word_list):
                sentance.insert(i+1, '/')
        #앞에 숫자 있을 때 초성 종성 구분
        if any(str in sentance[i+1] for str in num_word_list):
            if any(str in sentance[i-1] for str in middle_word_list):
                if any(str in sentance[i-2] for str in first_word_list):
                    sentance.insert(i+1, '/')
        #앞에 영어 있을 때 초성 종성 구분
        if any(str in sentance[i+1] for str in abc_word_list):
            if any(str in sentance[i-1] for str in middle_word_list):
                if any(str in sentance[i-2] for str in first_word_list):
                    sentance.insert(i+1, '/')
        
print(sentance)
#cnt = len(sentance) #count sentence len
com_len(sentance)
    


